services:
  mlflow:
    build:
      context: ./mlflow
    image: mlops/mlflow-recap:latest
    container_name: mlflow-recap-20a
    ports:
      - "5000:5000"
    volumes:
      - mlflow-db:/mlflow/database
      - mlflow-artifacts:/mlflow/mlruns
      - .:/work
    working_dir: /work
    restart: unless-stopped

volumes:
  mlflow-db:
  mlflow-artifacts:
